version: '3.8'

services:
  tls-server:
    build:
      context: .
    container_name: gost-server
    ports:
      - "4433:4433"
    command: ./build/server
    networks:
      - gost-net

  tls-client:
    build:
      context: .
    container_name: gost-client
    depends_on:
      - tls-server
    command: ./build/client gost-server 4433
    networks:
      - gost-net

networks:
  gost-net:
    driver: bridge
